main: me.wsman217.FlyPlugin.Main
name: FlightTimer
version: 1.2
author: wsman217
description: A plugin that allows you to fly without creative.
commands: 
  fly: 
    description: Allows or takes away flight.
    usage: /fly <player> 
    permission: fly.command.use
    
  flytimer:
    description: Allows user to create the Feather Of Flight
    permission: fly.item.create
permissions:
  fly.command.use: 
    descritption: Allows user to use /fly
    default: op
    
  fly.item.create: 
    description: Allows user to create the Feather Of Flight
    default: op